export const SIGN_IN_FETCHING = 'SIGN_IN_FETCHING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const REGISTER_USER_FETCHING = 'REGISTER_USER_FETCHING';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const CREATE_MENU_FETCHING = 'CREATE_NEW_MENU_FETCHING';
export const CREATE_MENU_SUCCESS = 'CREATE_NEW_MENU_SUCCESS';
export const CREATE_MENU_FAILURE = 'CREATE_NEW_MENU_FAILURE';
